name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t mlops-prod .

      - name: Run smoke container
        run: |
          docker run --rm \
            -e MLFLOW_TRACKING_URI="${{ secrets.MLFLOW_TRACKING_URI }}" \
            -e MLFLOW_TRACKING_USERNAME="${{ secrets.MLFLOW_TRACKING_USERNAME }}" \
            -e MLFLOW_TRACKING_PASSWORD="${{ secrets.MLFLOW_TRACKING_PASSWORD }}" \
            -e MODEL_URI="${{ vars.MODEL_URI }}" \
            mlops-prod